### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by stevenrbrandt** [octapps/octapps#12]
I left details on your JOSS review. Did you see? Thanks.
https://github.com/openjournals/joss-reviews/issues/707

**Comment by kwwette** [comment]
@stevenrbrandt Yes I saw, thanks very much! Having a look at this now ...

**Comment by kwwette** [comment]
@stevenrbrandt Btw the Dockerfile you wrote is very useful - would it be okay if I added it (with some updates) to OctApps itself?

**Comment by stevenrbrandt** [comment]
Of course!

--Steve

**Comment by kwwette** [comment]
@stevenrbrandt The tests should be fixed now.

FYI the test you reported failing was because I'd forgotten to list `pkg-config` as a dependency, which meant that the build system was silently failing to build some modules. Once that was fixed, I also found some tests failed under Docker because the LALSuite packages available for Debian jessie are quite old and were missing some features. I've now made the tests backward-compatible with the Debian jessie packages.

You should now be able to run `docker build https://github.com/octapps/octapps.git` to build and test OctApps under Debian jessie. Please confirm this now works, then I'll close this issue.
