### ISSUE TITLE
Fix lalsuite CI build (Ubuntu)

### ISSUE THREAD

**Issue by ReinhardPrix** [octapps/octapps#34]
currently the travis build for configuration (linux trusty, DOCKER=no) fails in the lalsuite build step
with (eg see https://travis-ci.org/octapps/octapps/builds/461331589 build job 140.1)
```
CXX      swiglal_octave_la-swiglal_octave.lo
swiglal_octave.cpp: In function ‘octave_value_list _wrap_gsl_vector_short_data_set(const octave_value_list&, int)’:
swiglal_octave.cpp:19928:16: error: storage size of ‘dims2’ isn’t known
   size_t dims2[] ;
               ^
```

@kwwette Karl, I'm at a bit of a loss wrt to the travis setup, could you maybe have a look?
Otherwise I guess we could simply take out the 'DOCKER=no' config, as the 'DOCKER=yes' one seems to pass just fine ?! (not sure either what the differences are)

**Comment by kwwette** [comment]
Hi @ReinhardPrix, the DOCKER=no builds against the latest LALSuite checkout, whereas DOCKER=yes builds against a packaged version (currently jessie). Not sure why DOCKER=no is failing, and afraid don't have time to debug now, so I suggest disabling it for now.

**Comment by kwwette** [comment]
- Fixed the DOCKER=no build so should work now. Since this job builds against the latest LALSuite checkout, I've set this job as allowed to fail so as not to break the CI build.
- OSX build no no longer builds SWIG extensions, as OSX Octave version is too new for SWIG.
- Documentation now built in separate job so not affected by failing tests.

**Comment by ReinhardPrix** [comment]
great, thanks!
